DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `games`;
DROP TABLE IF EXISTS `user-owned-games`;
DROP TABLE IF EXISTS `places`;
DROP TABLE IF EXISTS `characters`;
DROP TABLE IF EXISTS `collectibles`;


CREATE TABLE `users` (
`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
`name` VARCHAR(255) NOT NULL,
`password` VARCHAR(255) NOT NULL,
`register-date` DATETIME NOT NULL DEFAULT now());

CREATE TABLE `games` (
`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
`name` VARCHAR(255) NOT NULL,
`priceUSD` INT NOT NULL,
`platform` VARCHAR(255) NOT NULL);

CREATE TABLE `user-owned-games` (
`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
`userID` INT NOT NULL,
`gameID` INT NOT NULL);

CREATE TABLE `places` (
`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
`name` VARCHAR(45) NOT NULL,
`numberOfEnemy` INT NOT NULL,
`gameID` INT NOT NULL);

CREATE TABLE `characters` (
`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
`name` VARCHAR(45) NOT NULL,
`sex` VARCHAR(45) NOT NULL,
`age` INT NOT NULL,
`power` INT NOT NULL,
`race` VARCHAR(45) NOT NULL,
`gameID` INT NOT NULL);

CREATE TABLE `collectibles` (
`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
`name` VARCHAR(45) NOT NULL,
`rarity` VARCHAR(45) NOT NULL,
`maxValuee` INT NOT NULL DEFAULT 999999,
`gameID` INT NOT NULL);

ALTER TABLE `user-owned-games` ADD CONSTRAINT `user-owned-games_userID_users_id` FOREIGN KEY (`userID`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `user-owned-games` ADD CONSTRAINT `user-owned-games_gameID_games_id` FOREIGN KEY (`gameID`) REFERENCES `games`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `places` ADD CONSTRAINT `places_gameID_games_id` FOREIGN KEY (`gameID`) REFERENCES `games`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `characters` ADD CONSTRAINT `characters_gameID_games_id` FOREIGN KEY (`gameID`) REFERENCES `games`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `collectibles` ADD CONSTRAINT `collectibles_gameID_games_id` FOREIGN KEY (`gameID`) REFERENCES `games`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
